// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type DigitCaptchaReq struct {
}

type DigitCaptchaResp struct {
	CaptchaId  string `json:"captchaId"`
	CaptchaImg string `json:"captchaImg"`
}

type EmailCaptchaReq struct {
	Email string `json:"email"`
}

type EmailCaptchaResp struct {
	CaptchaId string `json:"captchaId"`
}

type RotateCaptchaReq struct {
}

type RotateCaptchaResp struct {
	CaptchaId   string `json:"captchaId"`
	ImageBase64 string `json:"imageBase64"`
	ThumbBase64 string `json:"thumbBase64"`
	ParentSize  int    `json:"parentSize"`
	ChildSize   int    `json:"childSize"`
}

type VerifyCaptchaReq struct {
	CaptchaType string `json:"captchaType"`
	CaptchaId   string `json:"captchaId"`
	Answer      string `json:"answer"`
}

type VerifyCaptchaResp struct {
	Success bool `json:"success"`
}
