// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2
// Source: chat.proto

package server

import (
	"context"

	"graph-med/app/chat/rpc/internal/logic"
	"graph-med/app/chat/rpc/internal/svc"
	"graph-med/app/chat/rpc/pd"
)

type ChatServer struct {
	svcCtx *svc.ServiceContext
	pd.UnimplementedChatServer
}

func NewChatServer(svcCtx *svc.ServiceContext) *ChatServer {
	return &ChatServer{
		svcCtx: svcCtx,
	}
}

func (s *ChatServer) CreateChatSession(ctx context.Context, in *pd.CreateChatSessionReq) (*pd.CreateChatSessionResp, error) {
	l := logic.NewCreateChatSessionLogic(ctx, s.svcCtx)
	return l.CreateChatSession(in)
}
