version: '3'

services:

  #prometheus监控 — Prometheus for monitoring
  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: prometheus
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    volumes:
      - ./deploy/prometheus/server/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus/data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    restart: always
    user: root
    ports:
      - 9090:9090
    networks:
      - graph_med_net

  #查看prometheus监控数据 - Grafana to view Prometheus monitoring data
  grafana:
    image: grafana/grafana:8.0.6
    container_name: grafana
    hostname: grafana
    user: root
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - ./data/grafana/data:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - graph_med_net

  redis:
    image: redis:6.2.5
    container_name: redis
    ports:
      - 6379:6379
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/redis/data:/data:rw
    command: "redis-server"
    privileged: true
    restart: always
    networks:
      - graph_med_net

#  neo4j:
#    image: neo4j
#    container_name: neo4j
#    ports:
#      - 7687:7687
#      - 7474:7474
#    environment:
#      NEO4J_AUTH: neo4j/password
#    volumes:
#      - ./data/neo4j/data:/data
#      - ./data/neo4j/logs:/logs
#    command: "neo4j start"
#    privileged: true
#    restart: always
#    networks:
#      - graph_med_net

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./data/mongo/data:/data/db
    command: "mongod"
    privileged: true
    restart: always
    networks:
      - graph_med_net


networks:
  graph_med_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16