// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	"graph-med/app/captcha/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// digit captcha
				Method:  http.MethodPost,
				Path:    "/gen/digit",
				Handler: digitHandler(serverCtx),
			},
			{
				// email captcha
				Method:  http.MethodPost,
				Path:    "/gen/email",
				Handler: emailHandler(serverCtx),
			},
			{
				// rotate captcha
				Method:  http.MethodPost,
				Path:    "/gen/rotate",
				Handler: rotateHandler(serverCtx),
			},
			{
				// verify captcha
				Method:  http.MethodPost,
				Path:    "/verify",
				Handler: verifyHandler(serverCtx),
			},
		},
		rest.WithPrefix("/captcha/v1"),
	)
}
