// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/monc"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

var prefixMcpServiceCacheKey = "cache:mcpService:"

type mcpServiceModel interface {
	Insert(ctx context.Context, data *McpService) error
	FindOne(ctx context.Context, id string) (*McpService, error)
	Update(ctx context.Context, data *McpService) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
}

type defaultMcpServiceModel struct {
	conn *monc.Model
}

func newDefaultMcpServiceModel(conn *monc.Model) *defaultMcpServiceModel {
	return &defaultMcpServiceModel{conn: conn}
}

func (m *defaultMcpServiceModel) Insert(ctx context.Context, data *McpService) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	key := prefixMcpServiceCacheKey + data.ID.Hex()
	_, err := m.conn.InsertOne(ctx, key, data)
	return err
}

func (m *defaultMcpServiceModel) FindOne(ctx context.Context, id string) (*McpService, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data McpService
	key := prefixMcpServiceCacheKey + id
	err = m.conn.FindOne(ctx, key, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case monc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultMcpServiceModel) Update(ctx context.Context, data *McpService) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()
	key := prefixMcpServiceCacheKey + data.ID.Hex()
	res, err := m.conn.UpdateOne(ctx, key, bson.M{"_id": data.ID}, bson.M{"$set": data})
	return res, err
}

func (m *defaultMcpServiceModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, ErrInvalidObjectId
	}
	key := prefixMcpServiceCacheKey + id
	res, err := m.conn.DeleteOne(ctx, key, bson.M{"_id": oid})
	return res, err
}
