medical_attrs:
  疾病名称: name
  简介: brief
  是否属于医保: is_belong_to_medical_insurance
  别名: alias
  发病部位: disease_location
  传染性: transmission
  多发人群: disease_population
  就诊科室: department
  治疗费用: treatment_fee
  治愈率: cure_rate
  治疗周期: treatment_cycle
  早期症状: early_symptom
  晚期症状: late_symptom
  典型症状: typical_symptom
  相关症状: related_symptom
  症状描述: symptom_description
  病因描述: cause_description
  常见并发症: common_complication
  并发症描述: complication_description
  预防描述: prevention_description
  鉴别描述: identification_description
  治疗描述: treatment_description
  就诊-典型症状: treatment_typical_symptom
  最佳就诊时间: treatment_best_time
  就诊时长: treatment_duration
  复诊频率/诊疗周期: treatment_frequency
  就诊前准备: treatment_before
  常见问诊内容: treatment_common_inquiry
  重点检查项目: treatment_key_check
  诊断标准: diagnosis_standard
  常见检查: common_check_items
  检查描述: check_description
  护理描述: nursing_description
  饮食适宜: diet_suitable
  宜吃食物: diet_suitable_foods
  饮食禁忌: diet_unsuitable
  忌吃食物: diet_unsuitable_foods
  饮食描述: diet_description
